<li><table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="16%"><a href="[field:arcurl/]" title="[field:fulltitle/]" ><img src="[field:picname/]" width="82" height="80" /></a></td>
    <td width="84%" valign="top">
    <p class="c_blue"><a href="[field:arcurl/]" title="[field:fulltitle/]" >[field:title /]</a><!--<span class="f_12 c_666">（来源：[field:source /]）</span>--></p>
    <p class="f_12"><a href="[field:arcurl/]" title="[field:fulltitle/]" >[field:description/]......</a></p>
    </td>
  </tr>
</table>
</li>