<li  onmouseover="this.style.background='url(/skin/images/btn_over.jpg) left no-repeat';" onmouseout="this.style.background='url(/skin/images/btn_out.jpg) left no-repeat';">

          <table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td width="61" height="60" align="center">[field:pubdate function="GetDateMK(@me)" /]</td>

    <td width="739" height="60" align="left" style="padding-left:10px;" >   
     <p class="f_12 c_666"><a href="[field:arcurl/]"><strong class="f_14">[field:title/]</strong>
     </br>[field:description/]</a></p>
      </td>    
  </tr>
</table>
</li>