<?php
$z[0]=Array("channelartlist","\r\n      <li><a href=\"{dede:field name='typeurl'/\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n        <div class=\"subnav\">\r\n          <div>{dede:channel type='son'} <a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> {/dede:channel} </div>\r\n        </div>\r\n      </li>\r\n      ",1482,1881);
$z[0][4]['typeid']="{dede:field.typeid/";

?>