<?php
$z[0]=Array("global","",264,290);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",338,368);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",409,436);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",819,854);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n              <li>\r\n                <div class=\"box\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"281\" height=\"158\"  alt=\"[field:title /]\" />[field:title /]</a></div>\r\n              </li>\r\n              ",4243,4611);
$z[4][4]['row']="4";
$z[4][4]['typeid']="14";
$z[4][4]['titlelen']="20";
$z[4][4]['infolen']="90";
$z[4][4]['orderby']="pubdate";
$z[4][4]['orderway']="desc";
$z[4][4]['col']="1";
$z[4][4]['imgwidth']="82";
$z[4][4]['imgheight']="80";
$z[5]=Array("arclist","\r\n            <li  onmouseover=\"this.style.background='url(/skin/images/btn_over.jpg) left no-repeat';\" onmouseout=\"this.style.background='url(/skin/images/btn_out.jpg) left no-repeat';\">\r\n              <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                <tr>\r\n                  <td width=\"61\" height=\"60\" align=\"center\">[field:pubdate function=\"GetDateMK(@me)\" /]</td>\r\n                  <td width=\"480\" height=\"60\" align=\"left\" style=\"padding-left:10px;\" >\r\n                    <p class=\"f_12 c_666\"><a href=\"[field:arcurl/]\"><strong class=\"f_14\">[field:title /]</strong></a>\r\n                      </br>[field:description/]\r\n                    </p>\r\n                  </td>\r\n                </tr>\r\n              </table>\r\n            </li>\r\n            ",6268,7200);
$z[5][4]['row']="4";
$z[5][4]['typeid']="2";
$z[5][4]['titlelen']="60";
$z[5][4]['infolen']="90";
$z[5][4]['orderby']="pubdate";
$z[5][4]['orderway']="desc";
$z[5][4]['col']="1";
$z[5][4]['imgwidth']="82";
$z[5][4]['imgheight']="80";
$z[6]=Array("include","",8529,8566);
$z[6][4]['filename']="footer.htm";

?>